#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""AccuLynx -> CRM parity verdict.

Compares the migrated CRM dataset against AccuLynx's own reference totals and prints a
cancel-ready verdict: counts + financial totals within tolerance, per-entity gaps listed.

Usage:
    python scripts/parity_compare.py [--db data/crm_migration.db] [--ref docs/acculynx_reference.json]

The CRM side is read live from the SQLite DB. The AccuLynx side comes from a small JSON the
owner fills in from AccuLynx's reports (see docs/acculynx_reference.example.json). Without it,
the script prints the CRM baseline only and reports "reference missing" (not a pass).

No third-party deps. Money columns are TEXT; parsed the same way the fixed theme.est_num does
(honors leading '-' / surrounding parens as negative; multi-dot -> 0).
"""
import argparse, json, os, re, sqlite3, sys

COUNT_TABLES = ["leads", "contacts", "jobs", "estimates", "invoices", "payments",
                "measurements", "library_docs", "photos", "roof_reports"]
# default tolerances: counts must match within 1% (migration can legitimately drop a few
# canceled/junk rows); financial totals within 1%.
DEFAULT_TOL = {"count": 0.01, "money": 0.01}


def money(s):
    if s is None:
        return 0.0
    s = str(s)
    neg = s.strip().startswith("(") or s.strip().startswith("-")
    v = re.sub(r"[^0-9.]", "", s)
    try:
        f = float(v) if v and v.count(".") < 2 else 0.0
    except ValueError:
        f = 0.0
    return -f if neg else f


def crm_side(db):
    if not os.path.exists(db):
        sys.exit("DB not found: %s" % db)
    c = sqlite3.connect(db)
    cur = c.cursor()
    tabs = {r[0] for r in cur.execute("select name from sqlite_master where type='table'")}
    counts = {}
    for t in COUNT_TABLES:
        counts[t] = cur.execute("select count(*) from %s" % t).fetchone()[0] if t in tabs else None
    fin = {"contract_value": 0.0, "collected": 0.0, "invoiced": 0.0, "payments": 0.0}
    if "jobs" in tabs:
        for cv, co in cur.execute("select contract_value, collected from jobs"):
            fin["contract_value"] += money(cv)
            fin["collected"] += money(co)
    if "invoices" in tabs:
        fin["invoiced"] = sum(money(r[0]) for r in cur.execute("select amount from invoices"))
    if "payments" in tabs:
        fin["payments"] = sum(money(r[0]) for r in cur.execute("select amount from payments"))
    c.close()
    return counts, fin


def verdict(crm, ref, tol, kind):
    """Return (ok, pct_gap_str). ref None -> unknown."""
    if ref is None:
        return None, "no reference"
    if crm is None:
        return False, "CRM table missing"
    if ref == 0:
        return (crm == 0), "ref=0"
    gap = abs(crm - ref) / float(ref)
    return gap <= tol[kind], "%.1f%%" % (gap * 100)


def _vmark(crm, ref, tol, kind):
    ok, gap = verdict(crm, ref, tol, kind)
    return ("?" if ref is None else "-") if ok is None else ("PASS" if ok else "FAIL"), gap


def _render_md(crm, ref, tol):
    """Markdown PARITY PROOF from a --json blob (crm) + optional AccuLynx reference."""
    counts = crm.get("counts", {}); fin = crm.get("financials", {})
    dept = crm.get("by_department", {})
    rc = (ref or {}).get("counts", {}); rf = (ref or {}).get("financials", {})
    L = ["# AccuLynx -> CRM Parity Proof — 2026-06-11",
         "", "Generated by `parity_compare.py --render` from the live CRM (`%s`)." % crm.get("db", "?"),
         "" if ref else "\n> NOTE: No AccuLynx reference supplied — counts/financials shown, verdict BLOCKED.\n",
         "## Counts", "", "| Entity | CRM | AccuLynx | gap | |", "|---|---|---|---|---|"]
    fails = []
    for t in sorted(counts):
        m, g = _vmark(counts.get(t), rc.get(t), tol, "count")
        if m == "FAIL": fails.append("count:" + t)
        L.append("| %s | %s | %s | %s | %s |" % (t, counts.get(t), rc.get(t, "?"), g, m))
    L += ["", "## Financials", "", "| Metric | CRM | AccuLynx | gap | |", "|---|---|---|---|---|"]
    for k in ["contract_value", "invoiced", "collected", "payments"]:
        m, g = _vmark(fin.get(k), rf.get(k), tol, "money")
        if m == "FAIL": fails.append("money:" + k)
        rv = "$%s" % format(rf[k], ",.0f") if k in rf else "?"
        L.append("| %s | $%s | %s | %s | %s |" % (k, format(fin.get(k, 0), ",.0f"), rv, g, m))
    L += ["", "## Per department (CRM)", "", "| Dept | jobs | contract_value | invoiced | collected |", "|---|---|---|---|---|"]
    for d in sorted(dept, key=lambda x: -dept[x].get("contract_value", 0)):
        e = dept[d]
        L.append("| %s | %s | $%s | $%s | $%s |" % (
            d, e.get("jobs", 0), format(e.get("contract_value", 0), ",.0f"),
            format(e.get("invoiced", 0), ",.0f"), format(e.get("collected", 0), ",.0f")))
    L += ["", "## Verdict", ""]
    if ref is None:
        L.append("**BLOCKED** — supply `docs/acculynx_reference.json` to judge parity.")
    elif fails:
        L.append("**NOT cancel-ready.** Gaps: " + ", ".join(fails))
    else:
        L.append("**PASS - parity within tolerance; AccuLynx is safe to cancel.**")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default="data/crm_migration.db")
    ap.add_argument("--ref", default="docs/acculynx_reference.json")
    ap.add_argument("--json", action="store_true",
                    help="emit measured data as JSON — run this where the LIVE DB is "
                         "(e.g. Render shell) and post the JSON back to crm-ui to render the proof")
    ap.add_argument("--render", metavar="CRM_JSON",
                    help="render a markdown PARITY PROOF from a saved --json blob + the reference")
    a = ap.parse_args()

    if a.render:
        crm = json.load(open(a.render))
        ref = json.load(open(a.ref)) if os.path.exists(a.ref) else None
        print(_render_md(crm, ref, DEFAULT_TOL))
        return

    counts, fin = crm_side(a.db)
    ref = json.load(open(a.ref)) if os.path.exists(a.ref) else None
    tol = DEFAULT_TOL

    if a.json:
        c2 = sqlite3.connect(a.db); cur2 = c2.cursor()
        jdept = {r[0]: (r[1] or "(none)") for r in cur2.execute(
            "select id, coalesce(nullif(department,''),'(none)') from jobs")}
        dept = {}
        for jid, cv, co in cur2.execute("select id, contract_value, collected from jobs"):
            e = dept.setdefault(jdept[jid],
                                {"jobs": 0, "contract_value": 0.0, "invoiced": 0.0, "collected": 0.0})
            e["jobs"] += 1; e["contract_value"] += money(cv); e["collected"] += money(co)
        for jid, amt in cur2.execute("select job_id, amount from invoices"):
            dept.setdefault(jdept.get(jid, "(unlinked)"),
                            {"jobs": 0, "contract_value": 0.0, "invoiced": 0.0, "collected": 0.0})["invoiced"] += money(amt)
        c2.close()
        print(json.dumps({"db": a.db, "counts": counts, "financials": fin, "by_department": dept}, indent=2))
        return

    print("AccuLynx -> CRM PARITY  (db=%s)" % a.db)
    print("=" * 64)
    if ref is None:
        print("!! AccuLynx reference missing (%s) - CRM baseline only, NOT a pass." % a.ref)
        print("   Fill it from docs/acculynx_reference.example.json\n")

    rc = (ref or {}).get("counts", {}) if ref else {}
    rf = (ref or {}).get("financials", {}) if ref else {}
    fails = []

    print("COUNTS                 CRM        AccuLynx     gap   verdict")
    for t in COUNT_TABLES:
        crmv = counts.get(t)
        refv = rc.get(t)
        ok, g = verdict(crmv, refv, tol, "count")
        mark = "-" if ok is None else ("PASS" if ok else "FAIL")
        if ok is False:
            fails.append("count:%s" % t)
        print("  %-18s %8s   %8s   %6s   %s" % (
            t, "-" if crmv is None else crmv, "?" if refv is None else refv, g, mark))

    print("\nFINANCIALS             CRM            AccuLynx       gap   verdict")
    for k in ["contract_value", "invoiced", "collected", "payments"]:
        crmv = fin.get(k, 0.0)
        refv = rf.get(k)
        ok, g = verdict(crmv, refv, tol, "money")
        mark = "-" if ok is None else ("PASS" if ok else "FAIL")
        if ok is False:
            fails.append("money:%s" % k)
        refstr = "?" if refv is None else ("$" + format(refv, ",.2f"))
        print("  {:<18} ${:>13}   {:>13}   {:>6}   {}".format(
            k, format(crmv, ",.2f"), refstr, g, mark))

    # per-department breakdown (CRM) — OVERLORD wants splits, not one pipeline
    _c = sqlite3.connect(a.db); _cur = _c.cursor()
    jdept = {r[0]: (r[1] or "(none)") for r in _cur.execute(
        "select id, coalesce(nullif(department,''),'(none)') from jobs")}
    dj, dv, dc = {}, {}, {}
    for jid, cv, co in _cur.execute("select id, contract_value, collected from jobs"):
        d = jdept[jid]
        dj[d] = dj.get(d, 0) + 1
        dv[d] = dv.get(d, 0.0) + money(cv)
        dc[d] = dc.get(d, 0.0) + money(co)
    di = {}
    for jid, amt in _cur.execute("select job_id, amount from invoices"):
        d = jdept.get(jid, "(unlinked)")
        di[d] = di.get(d, 0.0) + money(amt)
    _c.close()
    print("\nPER-DEPARTMENT (CRM)   jobs   contract_value       invoiced        collected")
    for d in sorted(dj, key=lambda x: -dv.get(x, 0)):
        print("  {:<18} {:>5}   ${:>13}   ${:>13}   ${:>13}".format(
            d[:18], dj[d], format(dv.get(d, 0), ",.2f"),
            format(di.get(d, 0), ",.2f"), format(dc.get(d, 0), ",.2f")))

    print("\n" + "=" * 64)
    if ref is None:
        print("VERDICT: BLOCKED - provide AccuLynx reference totals to judge parity.")
        sys.exit(2)
    if fails:
        print("VERDICT: NOT cancel-ready. Gaps: %s" % ", ".join(fails))
        sys.exit(1)
    print("VERDICT: PASS - parity within tolerance; AccuLynx is safe to cancel.")
    sys.exit(0)


if __name__ == "__main__":
    main()
